/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "stdio.h"
#include <Graphics.hpp>
#include <Arduino.h>
#include <pins.h>
#include "CException.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_reset_screen_does_clear_the_screen();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Suite Setup=====*/
void suiteSetUp(void)
{
Serial.begin(9600); init_graphics(LCD_PINS); delay(1000);
}

/*=======Suite Teardown=====*/
int suiteTearDown(int num_failures)
{
return num_failures; } void loop() {
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        volatile CEXCEPTION_T e;
        Try {
            setUp();
            func();
        } Catch(e) {
            TEST_ASSERT_EQUAL_HEX32_MESSAGE(CEXCEPTION_NONE, e, "Unhandled Exception!");
        }
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/

/*=======MAIN=====*/
int run(void); void setup() {run();} int run(void);
int run(void)
{
  suiteSetUp();
  UnityBegin("test/test_lcd_graphics/test_remote_lcd_graphics.cpp");
  run_test(test_reset_screen_does_clear_the_screen, "test_reset_screen_does_clear_the_screen", 20);

  return suiteTearDown(UNITY_END());
}
